// Reads src/content/posts/*.md and writes src/app/posts/posts-data.generated.ts.
// Runs as a `prebuild` hook so `ng build` always sees fresh post data.

import { readFileSync, readdirSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import matter from 'gray-matter';
import { marked } from 'marked';

const here = dirname(fileURLToPath(import.meta.url));
const postsDir = join(here, '..', 'src', 'content', 'posts');
const outFile = join(here, '..', 'src', 'app', 'posts', 'posts-data.generated.ts');

marked.setOptions({ gfm: true, breaks: false });

const files = existsSync(postsDir)
  ? readdirSync(postsDir).filter((f) => f.endsWith('.md'))
  : [];

// YAML auto-parses unquoted ISO dates into JS Date objects.
// Normalize back to a 'YYYY-MM-DD' string so sorting is chronological.
const toIsoDate = (d) =>
  d instanceof Date ? d.toISOString().slice(0, 10) : String(d);

const posts = files.map((filename) => {
  const raw = readFileSync(join(postsDir, filename), 'utf8');
  const { data, content } = matter(raw);
  if (!data.title) throw new Error(`${filename}: missing 'title' in frontmatter`);
  if (!data.date) throw new Error(`${filename}: missing 'date' in frontmatter (YYYY-MM-DD)`);
  return {
    slug: filename.replace(/\.md$/, ''),
    title: String(data.title),
    date: toIsoDate(data.date),
    description: String(data.description ?? ''),
    html: marked.parse(content),
  };
});

posts.sort((a, b) => b.date.localeCompare(a.date));

const banner =
  '// AUTO-GENERATED by scripts/generate-posts.mjs — do not edit by hand.\n' +
  '// Regenerated on every `npm run build` from src/content/posts/*.md.\n\n';
const body =
  "import type { Post } from './post';\n\n" +
  `export const posts: readonly Post[] = ${JSON.stringify(posts, null, 2)};\n`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, banner + body);

console.log(`generate-posts: wrote ${posts.length} post(s) → ${outFile.replace(here + '/..', '.')}`);
